
name: action-createBranch 

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      branchName:
        type: string
        required: true
      branchType:
        type: choice
        description: Branch type
        options:
        - hotfix
        - feature
        - development    
  workflow_call:
    inputs:
      branchName:
        type: string
        required: true
      branchType:
        type: string
        description: Branch type
jobs:
  createbranch:
    runs-on: ubuntu-latest
    steps: 
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         branch: ${{ inputs.branchType }}-${{ inputs.branchName }}
