name: action-packsolution 

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      solution-name:
        description: "Solution Name"
        type: string
        required: true
        default: 'OrgDemo'
      branch-name:
        type: string
        required: true
      folder-path:
        type: string
        required: false
        default: '.'

jobs:
  # This workflow contains a single job called "build"
  export:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set release-date
        run: |
          $releasedate = (Get-Date).toString('yyyyMMdd');
          echo "release-date=$releasedate"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      - name: Set source-path
        run: |
          write-host "${{ inputs.folder-path }}";
          write-host $inputs.'folder-path';
          if (($inputs.'folder-path').length -gt 1 ){
            $folderPath = $inputs.'folder-path' + '/src/' + $inputs.'solution-name'
            $releasePath = $inputs.'folder-path' + '/release/'+ $ENV.'release-date' + '/' + $inputs.'solution-name'
          } else
          {
            $folderPath = 'src/' + $inputs.'solution-name'
            $releasePath = 'release/'+ $ENV.'release-date' + '/' + $inputs.'solution-name'
          }
          echo "source-path=$folderPath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "release-path=$releasePath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
      - name: Set release-path if empty
        if: ${{ inputs.folderPath }} == '.'
        run: echo "release-path=$('release/${{ env.release-date }}/')" >> "$GITHUB_ENV"
      - name: Set release-path if not empty
        if: ${{ inputs.folderPath }} <> '.' 
        run: echo "release-path=$('${{ inputs.folderPath }}/release/${{ env.release-date }}/')" >> "$GITHUB_ENV"
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
           ref: ${{ inputs.branch-name }}
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      - uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-file: ${{ inputs.folderPath }}/release/${{ env.release-date }}/${{ inputs.solution-name }}.zip
          solution-folder: ${{ inputs.folderPath }}/src/${{ inputs.solution-name }}
          solution-type: Both
      - name: Commit to relase branch
        if: ${{ inputs.isCommit }} == true
        uses: EndBug/add-and-commit@v9
        with: 
          message: ${{ inputs.commitMessage }}
          new_branch: ${{ github.GITHUB_REF }}
          add: '${{ inputs.folderPath }}/release/. --force'
