name: Deploy Solution with Actions

on:
  pull_request:
     branches:
      - 'release/**'
      - 'main'
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch-type:
        required: false
        type: choice
        options:
        - feature
        - hotfix
        - development
        - main
        default:
          main
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  ''
jobs:
  deploy-setup:
    environment: 'Contoso Staging'
    runs-on: ubuntu-latest
    steps: 
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - name: Variables      
      run: |        
        write-Host "ref ${{ github.ref }}"        
        write-Host "GITHUB_REF ${{ github.GITHUB_REF }}"
        if $( $inputs.'branch-type' -eq 'main')
        {
          $branchName = 'main'
        } else {
          $branchName = $inputs.'branch-type' + '/' +$inputs.'branch-name'
        }
        echo "branch-name=$branchName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;

      shell: pwsh
  deploy-staging:
    needs: [deploy-setup]
    uses: adminMngEnvMCAP157851/PowerPlatformALM/.github/workflows/action-import-solution.yml@main
    with: 
      environment: 'Contoso Staging'
      solution-name: ${{ inputs.solution-name }}
      branch-name: '${{ env.branch-name }}'
      folder-path: '.'
    secrets: inherit
