name: Deploy Solution

on:
  workflow_run:
    workflows: ["Pack Solution"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  set-target:    
    runs-on: ubuntu-latest        
    environment: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}        
    steps:        
    - name: Use variables           
      run: |                
        echo "variable : var URI ${{ vars.POWERPLATFORMORGURI }}"                
        echo "variable Target ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"                
        echo "variable Source ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}"        
    - name : set varable            
      uses: marcdomain/set-variables@v1            
      with:                
        variables: |                    
          POWERPLATFORMURI: "${{ vars.POWERPLATFORMORGURI }}"        
    - name : check variable            
      run: |                  
        echo "uri : ${{ vars.POWERPLATFORMORGURI }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution

      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ vars.POWERPLATFORMURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-file: ${{ vars.POWERPLATFORMSOLUTIONNAME }}_managed.zip

