# This workflow is triggered manually (workflow_dispatch) and deploys an unmanaged solution to a target environment
# inputs parameters:
# solution-name: name of the solution to worked on from Power Platform
# branch-type: type of branch
# branch-name: name of the git branch
# target-environment: Target environment
# Author: William Tsoi (Microsoft)
# Date: 2024-07-16
# Required reuseable workflows: workflow-import-solution.yml
name: Deploy Unmanaged Solution with Actions

on:
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch-type:
        required: false
        type: choice
        options:
        - feature
        - hotfix
        - development
        - main
        default:
          main
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  ''
      target-environment:
        description: 'Target environment'
        type: environment
        required: true
        default: 'Contoso Development'

jobs:
  deploy-staging-setup:
    environment: 'Contoso Staging'
    runs-on: ubuntu-latest
    steps: 
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - name: Variables      
      run: |        
        write-Host "ref ${{ github.ref }}"        
        write-Host "GITHUB_REF ${{ github.GITHUB_REF }}"
      shell: pwsh
  deploy-staging:
    needs: [deploy-staging-setup]
    uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-import-solution.yml@main
    with: 
      environment:  ${{ inputs.target-environment }}
      solution-name: ${{ inputs.solution-name }}
      branch-name: '${{ inputs.branch-name }}'
      branch-type: '${{ inputs.branch-type }}'
      folder-path: '.'
      managed: false
    secrets: inherit
