name: Deploy Solution

on:
  workflow_run:
    workflows: ["Pack Solution"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution

      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ vars.POWERPLATFORMURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-file: ${{ vars.POWERPLATFORMSOLUTIONNAME }}_managed.zip

