name: Deploy Solution

on:
  workflow_run:
    workflows: ["Pack Solution"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
  
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}  
jobs:
  deploy:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}

    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pack-solution.yml
          name: packed-solution

      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONURI}}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-file: contoso_university_core_managed.zip

