name: Deploy Solution with Actions

on:
  pull_request:
     branches:
      - 'release/**'
      - 'main'
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch-type:
        required: false
        type: choice
        options:
        - feature
        - hotfix
        - development
        - main
        default:
          main
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  ''
jobs:
  deploy-setup:
    environment: 'Contoso Staging'
    runs-on: ubuntu-latest
    steps:    
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - name: Variables      
      run: |        
        echo "Solution Name :'contoso_university_core'"        
        echo "ref ${{ github.ref }}"        
        echo "GITHUB_REF ${{ github.GITHUB_REF }}"   
  deploy-staging:
    needs: [deploy-setup]
    uses: adminMngEnvMCAP157851/PowerPlatformALM/.github/workflows/action-import-solution.yml@main
    with: 
      environment: 'Contoso Staging'
      solutionName: ${{ inputs.solution-name }}
      folderPath: '.'
    secrets: inherit
