# This workflow will export the solution from the development environment to the source control repository.
# inputs parameters:
# solution-name: name of the solution to worked on from Power Platform
# branch-name: name of the git branch
# branch-type: type of branch
# source-Environment: Source Development Environment
# delete-existing-source: delete existing source file before export
# Author: William Tsoi (Microsoft)
# Date: 2024-07-16
# Required reuseable workflows: workflow-export-solution.yml

name: Export Solution From Dev with Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  '001'
      branch-type:
        description: 'type of branch'
        required: true
        type: choice
        options:
        - feature
        - hotfix
        - bugfix
        - development
      source-Environment:
        description: 'Source Development Environment'
        type: environment
        required: true
        default: 'Contoso Development'
      delete-existing-source:
        description: 'delete existing source file before export'
        type: boolean
        required: false
        default: false
jobs:
  setup:
    environment: ${{ inputs.source-Environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:    
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ github.event.inputs.solution-name }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem -Recurse | foreach { write-host $_.FullName }
  #createBranch:
  #  needs: [setup]
  #  uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-createBranch.yml@main
  #  with: 
  #    branch-name: ${{ inputs.branch-name }}
  #    branch-type: ${{ inputs.branch-type }}
  #  secrets: inherit
  export:
    needs: [setup]      
    uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-export-solution.yml@main
    with: 
      environment: ${{ inputs.source-Environment }}
      solution-name: ${{ inputs.solution-name }}
      ClearEnvironmentVariableValues: true
      isCommit: true
      branch-name: ${{ inputs.branch-name }}
      branch-type: ${{ inputs.branch-type }}
      commitMessage: 'Export Solution ${{ inputs.solution-name }}'
      folder-path: '.'
      VersionReleaseIncrement: 1
    secrets: inherit
       
