name: Export Solution From Dev with Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch-name:
        description: 'name of the git branch'
        required: false
        default:  '001'
      branch-type:
        description: 'type of branch'
        required: true
        type: choice
        options:
        - feature
        - hotfix
        - development
      sourceEnvironment:
        description: 'Source Development Environment'
        type: choice
        required: true
        options:
        - 'Contoso Development'
        - 'System Administrator Developer Environment'
        default: 'Contoso Development'
jobs:
  setup:
    environment: 'Contoso Development'
    runs-on: ubuntu-latest
    steps:    
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ github.event.inputs.solution-name }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem  -Recurse | foreach { write-host $_.FullName }
  #createBranch:
  #  needs: [setup]
  #  uses: adminMngEnvMCAP157851/PowerPlatformALM/.github/workflows/action-createBranch.yml@main
  #  with: 
  #    branch-name: ${{ inputs.branch-name }}
  #    branch-type: ${{ inputs.branch-type }}
  #  secrets: inherit
  export:
    needs: [setup]
    uses: adminMngEnvMCAP157851/PowerPlatformALM/.github/workflows/action-export-solution.yml@main
    with: 
      environment: ${{ inputs.sourceEnvironment }}
      solution-name: ${{ inputs.solution-name }}
      ClearEnvironmentVariableValues: true
      isCommit: true
      branch-name: ${{ inputs.branch-name }}
      branch-type: ${{ inputs.branch-type }}
      commitMessage: 'Export Solution ${{ inputs.solution-name }}'
      folderPath: '.'
      VersionReleaseIncrement: 1
    secrets: inherit
       
