name: Export Solution

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ vars.POWERPLATFORMSOLUTIONNAME }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    - name: Export Unmanaged Solution
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ vars.POWERPLATFORMORGURI_DEV }}
        app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
        client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
        tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
        solution-name: ${{ vars.POWERPLATFORMSOLUTIONNAME }}
        solution-output-file: '${{ vars.POWERPLATFORMSOLUTIONNAME }}.zip'
        overwrite: true
        managed: false
    - name: Export Managed Solution      
      uses: microsoft/powerplatform-actions/export-solution@v0          
      with:          
        environment-url: ${{ vars.POWERPLATFORMORGURI_DEV }}          
        app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}          
        client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}         
        tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}          
        solution-name: ${{ vars.POWERPLATFORMSOLUTIONNAME }}
        solution-output-file: '${{ vars.POWERPLATFORMSOLUTIONNAME }}_managed.zip'          
        overwrite: true          
        managed: true
    - name: Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Export Solution ${{ vars.POWERPLATFORMSOLUTIONNAME }}'
        add: '. --force'
        cwd: './solutions'