name: Export Solution

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}
    steps:
      - uses: microsoft/powerplatform-actions/export-solution@v0
        name: Export Unmanaged Solution
        with:
          environment-url: ${{ vars.POWERPLATFORMURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-output-file: Solutions\${{ vars.POWERPLATFORMSOLUTIONNAME }}.zip
          overwrite: true
          managed: false
      - uses: microsoft/powerplatform-actions/export-solution@v0        
        name: Export Unmanaged Solution        
        with:          
          environment-url: ${{ vars.POWERPLATFORMURI }}          
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}          
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}         
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}          
          solution-output-file: Solutions\${{ vars.POWERPLATFORMSOLUTIONNAME }}_managed.zip          
          overwrite: true          
          managed: true

