name: Export Solution From Dev with Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch_name:
        description: 'name of the git branch'
        required: false
        default:  'main'
jobs:
  setup:
    environment: 'Contoso Development'
    runs-on: ubuntu-latest
    steps:
    ##- uses: actions/checkout@v4
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ github.event.inputs.solution_name }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem  -Recurse | foreach { write-host $_.FullName }
        
  export:
    uses: adminMngEnvMCAP157851/PowerPlatformALM/.github/workflows/action-exportsolution.yml@main
    with: 
      environment: 'Contoso Development'
      solution-name: ${{ inputs.solution-name }}
    secrets: inherit
       
