name: Export Solution From Dev with Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
      branch_name:
        description: 'name of the git branch'
        required: false
        default:  'main'
jobs:
  export:
    runs-on: ubuntu-latest
    environment: 'Contoso Development'
    steps:
    ##- uses: actions/checkout@v4
    - name: Variables      
      run: |        
        echo "Solution Name : ${{ github.event.inputs.solution_name }}"        
        echo "URI ${{ vars.POWERPLATFORMURI }}"        
        echo "Source ${{ vars.POWERPLATFORMORGURI_DEV }}"   
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem  -Recurse | foreach { write-host $_.FullName }
    - uses: actions/action-exportsolution@main
      with: 
        environment-url: ${{ vars.POWERPLATFORMORGURI_DEV }}
        app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
        client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
        tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
        solution-name: ${{ inputs.solution-name }}
       
