name: Export Solution

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}
    steps:
      - name: Variables      
        run: |        
          echo "Solution Name : ${{ vars.POWERPLATFORMSOLUTIONNAME }}"        
          echo "URI ${{ vars.POWERPLATFORMURI }}"        
          echo "Source ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}"   
          echo "Target ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
      - name: Export Unmanaged Solution
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ vars.POWERPLATFORMURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-name: ${{ vars.POWERPLATFORMSOLUTIONNAME }}
          solution-output-file: Solutions/${{ vars.POWERPLATFORMSOLUTIONNAME }}.zip
          overwrite: true
          managed: false
      - name: Export Managed Solution      
        uses: microsoft/powerplatform-actions/export-solution@v0          
        with:          
          environment-url: ${{ vars.POWERPLATFORMURI }}          
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}          
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}         
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}          
          solution-name: ${{ vars.POWERPLATFORMSOLUTIONNAME }}
          solution-output-file: Solutions/${{ vars.POWERPLATFORMSOLUTIONNAME }}_managed.zip          
          overwrite: true          
          managed: true
			- name: Add and Commit
        uses: EndBug/add-and-commit@v8
          add: 'Solutions'
          author_name: 'System Admin'
          author_email: admin@MngEnvMCAP157851.onmicrosoft.com
