name: PR Triggered Pack Contoso_university_core solution with Actions 

on:
  push:
    branches:
      - 'development/**'
      - 'release/**'
      - 'hotfix/**'
      - 'main'
    paths:
      - 'src/contoso_university_core/**'
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
      - 'main'     
    paths:
      - 'src/contoso_university_core/**'
jobs:
  setup:
    environment: ${{ inputs.source-environment }}
    permissions:
      actions: read
      repository-projects: write
      contents: write
    runs-on: ubuntu-latest
    steps:    
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
        solution-name: 'contoso_university_core'
      run: |
        echo $EVENT_CONTEXT

    - name: Variables      
      run: |        
        echo "Solution Name : ${{ solution-name }}
        echo "ref ${{ github.ref }}"        
        echo $EVENT_CONTEXT.ref
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem  -Recurse | foreach { write-host $_.FullName }
  pack:
    uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-pack-solution.yml@main
    with: 
      solution-name: ${{ solution-name }}
      branch-name: '${{ EVENT_CONTEXT.ref }}'
