name: Pack Solution from Development
on:
  #push:
  #  paths:
  #    - src/**
  workflow_dispatch:
    inputs:
      solution-name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: release/${{ github.event.inputs.solution_name }}.zip
          solution-folder: src/${{ github.event.inputs.solution_name }}
          solution-type: Both
          process-canvas-apps: true
      - name: Export Solution
        uses: actions/actions-exportsolution@1
        with: 
          solution-name: ${{ inputs.solution-name }}
          
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:          
          message: 'Commit Solution ${{ github.event.inputs.solution-name }}'          
          add: 'release/* --force'  
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: release/
