name: Pack Solution
on:
  push:
    paths:
      - src/**
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default:  'contoso_university_core'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: release/${{ github.event.inputs.solution_name }}.zip
          solution-folder: src/${{ github.event.inputs.solution_name }}
          solution-type: Both
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:          
          message: 'Commit Solution ${{ github.event.inputs.solution_name }}'          
          add: 'release/* --force'  
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: release/