name: Pack Solution
on:
  push:
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/${{ vars.POWERPLATFORMSOLUTIONNAME}}.zip
          solution-folder: src
          solution-type: Both
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: out/
