name: PR Triggered Pack Contoso_university_core solution with Actions 

on:
  push:
    branches:
      - 'development/**'
      - 'release/**'
      - 'hotfix/**'
      - 'main'
    paths:
      - 'src/contoso_university_core/**'
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'
      - 'main'     
    paths:
      - 'src/contoso_university_core/**'
env:
  solution-name: 'contoso_university_core'
jobs:
  setup:
    environment: ${{ inputs.source-environment }}
    permissions:
      actions: read
      repository-projects: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT

    - name: Variables      
      run: | 
        echo "env Solution Name brace: ${{ env.solution-name }}"
        echo "ref ${{ github.ref }}"        
        echo "${{ env.EVENT_CONTEXT.ref }}"
    - name: variables pwsh
      run: |
        write-Host '${{ env.solution-name }}'
        write-Host '${{ env.EVENT_CONTEXT.ref }}'
      shell: pwsh
    - name: Debug output
      shell: pwsh
      run: |
        Get-ChildItem  -Recurse | foreach { write-host $_.FullName }
  pack-variables:
    runs-on: ubuntu-latest
    solution-name: ${{ steps.pack-variables.outputs.solution-name }}
    branch-name: ${{ steps.pack-variables.outputs.branch-name }}
    steps:
    - name: Set environment variables to output
      id: pack-variables
      run: |
        echo "solution-name=${{ env.solution-name }}" >> $GITHUB_ENV
        echo "branch-name=${{ github.ref }}" >> $GITHUB_ENV

  pack:
    uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-pack-solution.yml@main
    with: 
      solution-name: ${{ pack-variables.outputs.solution-name }}
      branch-name: '${{ pack-variables.outputs.branch-name }}'
