name: Pack Solution
on:
  push:
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: release/${{ vars.POWERPLATFORMSOLUTIONNAME}}.zip
          solution-folder: src/${{ vars.POWERPLATFORMSOLUTIONNAME}}
          solution-type: Both
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:          
          message: 'Upack Solution ${{ vars.POWERPLATFORMSOLUTIONNAME }}'          
          add: 'release/* --force'  
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: release/
