name: Release Contoso_University_core

on:
  release:
    types: [created]
env:
  solution-name: 'contoso_university_core'
  use-setting-file: true
  branch-type: 'main'
  branch-name: ''
permissions:
  contents: write

jobs:
  release-staging-setup:
    environment: 'Contoso Staging'
    runs-on: ubuntu-latest
    outputs:
      setting-file: ${{ steps.staging-setting-file-variables.outputs.setting-file }}
    steps: 
    - name: Staging Variables      
      run: |        
        write-Host "ref ${{ github.ref }}"        
        write-Host "GITHUB_REF ${{ github.GITHUB_REF }}"
        if ('${{ env.use-setting-file }}' -eq 'true')
        {
          if (Test-Path -LiteralPath "settings/${{ env.solution-name }}-Contoso Staging.json") {
            $settingFile = 'settings/${{ env.solution-name }}-Contoso Staging.json'
          } else {
            $settingFile = ''
          }        
        } else {
          $settingFile = ''
        }
        echo "setting-file=$settingFile" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append; 
      shell: pwsh
    - name: Set environment variables to output
      id: staging-setting-file-variables
      run: |
        echo "setting-file=${{ env.setting-file }}" >> "$GITHUB_OUTPUT"
  release-staging:
    needs: [release-staging-setup]
    uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-import-solution.yml@main
    with:
      environment: 'Contoso Staging'
      solution-name: ${{ env.solution-name }}
      branch-name: '${{ env.branch-name }}'
      branch-type: '${{ env.branch-type }}'
      folder-path: '.'
      settings-file: ${{ needs.release-staging-setup.outputs.setting-file }}
      managed: true
    secrets: inherit
  release-production-setup:
    needs: [release-staging]
    environment: 'Contoso Production'
    runs-on: ubuntu-latest
    outputs:
      setting-file: ${{ steps.production-setting-file-variables.outputs.setting-file }}
    steps: 
    - name: Production Variables      
      run: |        
        write-Host "ref ${{ github.ref }}"        
        write-Host "GITHUB_REF ${{ github.GITHUB_REF }}"
        if (${{ env.use-setting-file }} -eq $true)
        {

          if (Test-Path -LiteralPath "settings/${{ env.solution-name }}-Contoso Staging.json") {
            $settingFile = 'settings/${{ env.solution-name }}-Contoso Production.json'
          } else {
            $settingFile = ''
          }
        } else {
          $settingFile = ''
        }
        echo "setting-file=$settingFile" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append; 
      shell: pwsh
    - name: Set environment variables to output
      id: staging-setting-file-variables
      run: |
        echo "setting-file=${{ env.setting-file }}" >> "$GITHUB_OUTPUT"
  release-production:
    needs: [release-production-setup]
    uses: Contoso-Enterprise/PowerPlatformALM/.github/workflows/workflow-import-solution.yml@main
    with: 
      environment: 'Contoso Production'
      solution-name: ${{ env.solution-name }}
      branch-name: '${{ env.branch-name }}'
      branch-type: '${{ env.branch-type }}'
      folder-path: '.'
      settings-file: ${{ needs.release-production-setup.outputs.setting-file }}
      managed: true
    secrets: inherit
