name: Test variables
on:
  workflow_dispatch:

jobs:
  display-variables:
    name: Test
    runs-on: ubuntu-latest
    environment: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
        echo "variable : URI ${{ env.POWERPLATFORMURI }}"
        echo "variable Target ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
        echo "variable Source ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}"        