name: Test variables
on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}

jobs:
  display-variables:
    name: Test
    environment: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}
    steps:
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
        echo "variable : {{ $env.POWERPLATFORMURI }}"
        echo "variable from shell environment : $env_var"
        echo "variable from shell environment : ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"        