name: Test variables

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  display-variables:
    name: Test
    runs-on: ubuntu-latest
    environment: ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}
    steps:
    - name: Use variables 1
      run: |
        echo "repository variable : ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
        echo "variable : env URI ${{ env.POWERPLATFORMURI }}"
        echo "variable : var URI ${{ vars.POWERPLATFORMORGURI }}"
        echo "variable Target ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"
        echo "variable Source ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}"
    - name : set varable
      uses: marcdomain/set-variables@v1
        with:
          variables: |
            POWERPLATFORMURI: "${{ vars.POWERPLATFORMORGURI }}"
  display-variables-again:    
    name: Test2    
    runs-on: ubuntu-latest    
    steps:    
    - name: Use variables 2      
      run: |        
        echo "repository variable : ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"        
        echo "variable : env URI $envURI"      
        echo "variable : PPenv URI ${{ env.POWERPLATFORMTARGETENVIRONMENT.POWERPLATFORMURI }}"              
        echo "variable : var URI ${{ vars.POWERPLATFORMURI }}"        
        echo "variable Target ${{ vars.POWERPLATFORMTARGETENVIRONMENT }}"        
        echo "variable Source ${{ vars.POWERPLATFORMSOURCEENVIRONMENT }}"    