# This is a basic workflow to help you get started with Actions

name: workflow-import-solution 

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      solution-name:
        description: "Solution Name"
        type: string
        required: true
        default: 'OrgDemo'
      environment:
        type: string
        required: true
      branch-name:
        type: string
        required: false
      branch-type:
        type: string
        required: true
      folder-path:
        type: string
        required: false
        default: '.'
      release-name:
        type: string
        required: false
        default: '.'
      managed:
        type: boolean
        required: false
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export:
    environment: ${{ inputs.environment }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set branch variables
        run: |
          if ( $inputs.'branch-type' -eq 'main')
          {
            $branchName = 'main'
          } else {
            $branchName = $inputs.'branch-type' + '/' +$inputs.'branch-name'
          }
          echo "branch-name=$branchName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
        shell: pwsh
      - name: check-branch-exists
        id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@v1
        with:
          branch: ${{ inputs.branch-name }}
      - name: debug check exists
        run: echo "${{ steps.check-branch-exists.outputs }}"
      - name: Checkout branch if exists
        if: steps.check-branch-exists.outputs.exists == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
      - name: Checkout branch main
        if: steps.check-branch-exists.outputs.exists != 'true'
        uses: actions/checkout@v4
      - name: Set release variables
        run: |
          $solutionName = '${{ Inputs.solution-name }}';
          if (($inputs.'release-name').length -gt 1)
          {
            $releaseName = $inputs.'release-name'
            write-host "release name: $releaseName"     
            if (($inputs.'folder-path').length -gt 1 )
            {
              $releasePath = $inputs.'folder-path' + '/release/'+ $releaseName + '/'
            } else {
              $releasePath = 'release/' + $releaseName +'/'
            }
          } else {
            write-host "release name: null"     
            if (($inputs.'folder-path').length -gt 1 )
            {
              if (Test-Path -LiteralPath "$($inputs.'folder-path')/release") {
                write-host "tested $($inputs.'folder-path')/release successful"
                $latestRelease = Get-ChildItem -path "$($inputs.'folder-path')/release" -Directory | Sort-Object -Property 'CreationTime' -Descending -top 1
                $latestRelease | select *
                write-host "latest release: $($latestRelease.Name)"
                $releaseName = $latestRelease.name
                $releasePath = $inputs.'folder-path' + '/release/' + $releaseName + '/' 
              } else {
                write-Error "Release folder not found"
              }
            } else {
              if (Test-Path -LiteralPath "release") {
                write-host "tested release successful"
                $latestRelease = Get-ChildItem -path "release" -Directory | Sort-Object -Property 'CreationTime' -Descending -top 1
                $latestRelease | select *
                write-host "latest release: $($latestRelease.Name)"
                $releaseName = $latestRelease.name
                $releasePath = 'release/'+ $releaseName + '/'
              } else {
                write-Error "Release folder not found"
              }
            }
          }
          write-Host $releasePath;
          write-Host ${{ Inputs.solution-name}} ;
          echo "release-name=$releaseName" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
          echo "release-path=$releasePath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
        shell: pwsh
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1
      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
      #managed solution
      - name: check managed solution
        if: ${{ inputs.managed }} == true
        uses: microsoft/powerplatform-actions/check-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          path: '${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
      - name: import managed Solution
        if: ${{ inputs.managed }} == true
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-file: '${{ env.release-path }}${{ inputs.solution-name }}_managed.zip'
          #import-as-holding: true
          stage-and-upgrade: true
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: true
          deployment-settings-file: 'settings/${{ inputs.solution-name }}-${{ inputs.environment }}.json'
          run-asynchronously: true
      # unmanaged solution
      - name: check unmanaged solution
        if: ${{ inputs.managed }} == false
        uses: microsoft/powerplatform-actions/check-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          path: '${{ env.release-path }}${{ inputs.solution-name }}.zip'
      - name: Import Unmanaged Solution
        if: ${{ inputs.managed }} == false
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ vars.POWERPLATFORMORGURI }}
          app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
          client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
          tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
          solution-file: '${{ env.release-path }}${{ inputs.solution-name }}.zip'
          #import-as-holding: true
          stage-and-upgrade: true
          force-overwrite: true
          publish-changes: true
          use-deployment-settings-file: true
          deployment-settings-file: 'settings/${{ inputs.solution-name }}-${{ inputs.environment }}.json'
          run-asynchronously: true

      # - name: upgrade managed Solution
      #   uses: microsoft/powerplatform-actions/upgrade-solution@v1
      #   with:
      #     environment-url: ${{ vars.POWERPLATFORMORGURI }}
      #     app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
      #     client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
      #     tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
      #     solution-name: ${{ inputs.solution-name }}
      # - name: Publish Solution Customizations
      #   uses: microsoft/powerplatform-actions/publish-solution@v1
      #   with:
      #     environment-url: ${{ vars.POWERPLATFORMORGURI }}
      #     app-id: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTID }}
      #     client-secret: ${{ secrets.POWERPLATFORMMANAGEMENTCLIENTSECRET }}
      #     tenant-id: ${{ secrets.POWERPLATFORMCONTOSOPRODUCTIONTENANTID }}
