
name: action-createBranch 

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      branchName:
        type: string
        required: true
      branchType:
        type: choice
        description: Branch type
        options:
        - hotfix
        - feature
        - development    
  workflow_call:
    inputs:
      branchName:
        type: string
        required: true
      branchType:
        type: string
        description: Branch type
jobs:
  createbranch:
    runs-on: ubuntu-latest
    steps: 
    ##- uses: actions/checkout@v4
      - name: check-branch-exists
        id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@v1
        with:
          branch: ${{ inputs.branchType }}-${{ inputs.branchName }}
      - name: Branch exists
        if: steps.check-branch-exists.outputs.exists == 'true'
        run: echo '${{ inputs.branchType }}-${{ inputs.branchName }} Branch exists'
      
      - name: Branch not found
        if: steps.check-branch-exists.outputs.exists == 'false'
        run: echo '${{ inputs.branchType }}-${{ inputs.branchName }} Branch NOT FOUND'      
      - name: Create Branch
        if: steps.check-branch-exists.outputs.exists == 'false'  
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         branch: ${{ inputs.branchType }}/${{ inputs.branchName }}
